version: '3'

services:
  db:
    image: postgres
    volumes:
      - hrt-app-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  back:
    build: 
      context: ./back/
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "rm -f /hrt-apps-rails/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./back:/hrt-apps-rails
      - ./back/vendor/bundle:/hrt-apps-rails/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
  front:
    build: 
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: sh -c "npm start"
    ports:
      - "8000:3000"
volumes:
  hrt-app-data:
    driver: local
