default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  passowrd:

development:
  <<: *default
  database: hrt_apps_rails_development

test:
  <<: *default
  database: hrt_apps_rails_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: db/production.postgresql
  pool: 5
  username: test_postgre
  password:
