version: "3"
services:
  db:
    image: postgres
    volumes:
      - hrt-app-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: bash -c "rm -f tmp/pids/server.pid && /bin/bash"
    volumes:
      - .:/hrt-apps-rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true

volumes:
  hrt-app-data:
